### ISSUE TITLE
Python 3 support would be nice.

### ISSUE THREAD

**Issue by F483** [bmuller/kademlia#11]
It is already the year 2015 after all.

**Comment by F483** [comment]
Why close the issues? Do you not want to support python 3? I would be willing to port the project myself.

**Comment by bmuller** [comment]
Pull requests are absolutely welcome!  Snarky comments suggesting my personal time was misspent on Python 2 are not.

**Comment by F483** [comment]
Pull requests on the way and cheer up, your reading far to much into my comment.

**Comment by F483** [comment]
Do the unittests have adequate coverage that I can assume the project is ported if I get them to pass on py3?

**Comment by bmuller** [comment]
Unfortunately, no.  PR's containing additional tests are, of course, welcome too!
