### ISSUE TITLE
Problem adding many keys in one go

### ISSUE THREAD

**Issue by mikaelfrykholm** [bmuller/kademlia#14]
I have a problem adding lots of keys. The modified webserver.tac fails after 277 keys on my machine (consistently) with timeout on the rpc call.
Any ideas?
```python
 def render_POST(self, request):
        for i in range(10000):
            key = i
            #key = request.path.split('/')[-1]
            value = request.content.getvalue()
            log.msg("Setting %s = %s" % (key, value))
            self.kserver.set(key, value)
        return value

**Comment by bmuller** [comment]
Hey @mikaelfrykholm - can you post a link to:
1. the full modified webserver.tac, along with the output from running it
1. the code you're using to set values, along with the output from running it

Thanks!

**Comment by mikaelfrykholm** [comment]
Certainly!

webserver.tac
http://h45h.com/h3UJ-OMH6fFvMv7NedoFrMyEQYThsZJMrisUK3EQEE8=

logfile: (with noisy=True)
http://h45h.com/dPvoQjcyM8RwfYuS4ZNKInyIanbmgTtqdxZauu8zwzA=

and curl --data "asdasd" http://185.97.32.250:8080/1 to set the data

**Comment by bmuller** [comment]
Looks like you're UDP flood attacking :)  Try limiting to something like 10/second and then see how far you get.

**Comment by bmuller** [comment]
I'm going to mark this as resolved.  Feel free to reopen if it was/is still an issue.  Thanks!
