### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by prabodh1194** [bmuller/kademlia#17]
What is the use of standalone server in examples/server.tac?

**Comment by bmuller** [comment]
It's a node on the Kademlia network.  More nodes = more good.

**Comment by prabodh1194** [comment]
how do the nodes become aware of one another?

**Comment by bmuller** [comment]
You tell a new node just starting up about at least one other node in the network, then it can find every other node from there.

**Comment by prabodh1194** [comment]
So, I want to use this DHT and setup a simple data storage system. I have set three nodes in this system by running, server.tac on three individual nodes. How do I run programs to set and get key,value from this DHT?

**Comment by bmuller** [comment]
Look at `example.py` for a set/get example.  If you have any other questions, please email me.
