### ISSUE TITLE
README example in Python3.5 references Python2.x code.

### ISSUE THREAD

**Issue by danielquinn** [bmuller/kademlia#27]
The `setup.py` for this project's `python3.5` branch had one reference to `rpcudp>=3.0.0` which isn't in pypi, so things explode when you try to install it.  I'm not sure if there's anything that can be done about that so long as you don't feel rpcudp is ready for prime time though:

```
Could not find a version that satisfies the requirement rpcudp>=3.0.0 (from kademlia) (from versions: 0.1, 0.2, 0.3, 0.4, 1.0, 2.0, 2.1)
No matching distribution found for rpcudp>=3.0.0 (from kademlia)
```

However, kademilia *also* doesn't cite a dependency on `twisted` (though the `master` branch does).  This was a surprise when I was trying things out so I thought it worth mentioning as that's definitely a stable package you can reference in `setup.py`.

**Comment by danielquinn** [comment]
Wait a sec, I see what's happening, I'm using the example from the README, but that not updated in the Python3.5 branch, so it's still referencing Twisted.  After a grepping of the codebase, *twisted isn't used for the 3.5 branch* -- I get it now.

Well then I guess I'll rename this issue to something more relevant.

**Comment by bmuller** [comment]
Yep!  Other than updating the code to work with Python 3 and stripping out Twisted, I didn't update the README/docs/examples/etc.

**Comment by bmuller** [comment]
This is all updated.  Thanks!
