### ISSUE TITLE
Is kademlia moving to support ayncio only and not Twisted?

### ISSUE THREAD

**Issue by jMyles** [bmuller/kademlia#29]
Hey @bmuller.  Thanks so much for kademlia.

I just watched your talk, "Dont Overreact", from pygotham last year.  Brilliant stuff man.

My question: It sounded pretty certain at the end of the talk that you were only wanting to support ayncio in the future (presumably for this and other projects).  Is that decision official?

For my part, I really like Twisted and I suspect that Twisted will experience a substantial resurgence in the next couple of years.  I'd love for kademlia to be able to work on either one.

**Comment by bmuller** [comment]
You're welcome, @jMyles!  It's my intent to only support asyncio in the future - but I may be willing to marginally maintain a Twisted branch.  It's mostly based on my time availability and how I see the community moving.  I truly ❤️  Twisted and have been using it for over a decade - but I think I see most folks moving over to asyncio and, frankly, I think the code is so much cleaner.

By the way - I really like your school bus.  Let me know if you're ever in New York!

**Comment by jMyles** [comment]
OK, understood.  It looks like the documentation is currently still all about Twisted - is there an easy way to understand how to get going with Kademlia and asyncio?

**Comment by bmuller** [comment]
I need to update the docs - though the API is basically still the same.  I'll update the docs when I move the https://github.com/bmuller/kademlia/tree/python3.5 branch to master
