### ISSUE TITLE
Question about findNeighbors

### ISSUE THREAD

**Issue by cliftonm** [bmuller/kademlia#30]
It looks like this returns only contacts that the node knows about.  The Kademlia spec refers to a "node lookup" that hits its closest nodes with FIND_NODE RPC's to find closer nodes.  Is that implemented here?

Ah - I see that's implemented in SpiderCrawler.  OK, gotta see how/when that's called.  Sorry for the premature question, I'm trying to map the Kademlia spec to various implementations (and yours is at the top of readability and clean, across multiple languages I'm looking at) and the thing that's confusing me at the moment in the spec is when the crawl occurs (always, or just for FindNode, or for a specific other call?) and to what recursion depth FindNode crawls to (this last one is particularly of interest because I could see the crawler never ending.)

**Comment by bmuller** [comment]
The crawler ends when it can't find any nodes closer than ones it has previously seen (see [here](https://github.com/bmuller/kademlia/blob/master/kademlia/crawling.py#L97)).  If you have any other questions - please feel free to email me (trying to keep the issues clean except for possible issues).

**Comment by cliftonm** [comment]
Thank you Brian.  Do you have a direct email?  I'm in the process of
writing a C# implementation for Code Project, both as a contribution to the
community and as a way of deeply understanding the Kademlia specification
(there seems to be two specs!)  As I'm going through this process, I'm
finding that I'm referencing your code more and more as the authority
implementation.  I find your work to be excellent and helps to answer many
questions.  And I definitely envy Python and its ability to handle numbers
as large as 2^160 - in C#, I would have to resort to using the BigInteger
class!

Regards,

Marc


www.marcclifton.com
518.721.8353
 |
www.higherorderprogramming.com
*Change the way you interact with the world*

**Comment by bmuller** [comment]
Hey @cliftonm - thanks so much!  Glad you're finding the lib so useful!

Feel free to email the address on my profile page https://github.com/bmuller

Thanks!
