### ISSUE TITLE
'Server' object has no attribute 'close'

### ISSUE THREAD

**Issue by jMyles** [bmuller/kademlia#31]
In the asyncio example, a `close` method is called on a `Server` object, but Server has no such method:

https://github.com/bmuller/kademlia/blob/python3.5/examples/example.py#L30

Also, does it perhaps make more sense to call `server.close()` and `loop.close()` in a `finally` clause of the try block at the end there?

**Comment by bmuller** [comment]
Thanks @jMyles - fixed now!
