### ISSUE TITLE
findNeighbors (routing.py) - Is nsmallest even needed?

### ISSUE THREAD

**Issue by KammererTob** [bmuller/kademlia#4]
Hi,

i am not sure about this, but is `nsmallest` really needed for this method? As far as i can see it, the method selects at max `k`nodes from the buckets (while iteratively increasing the range to those nodes by selecting buckets more to the left or the right of the specified node). Since `nodes` would hold at max `k` nodes in the end, wouldn't `heapq.nsmallest(k, nodes)` just return the list as it is? Because there are never more than k nodes inside the list. 
Shouldn't this method just fill the list with nodes from whole buckets and only select the nsmallest nodes when we reach a count greater or equal than k? This would make sure that we really return the k-closest nodes to the given node.

As i said i could be completely wrong. And before i forget: Great code. I really appreciate it!

**Comment by bmuller** [comment]
You're right that `nodes` will not be larger than `k`.  However, the heap isn't used to restrict size - it's used to sort (`nsmallest` is just used to get `nodes` in sorted form from the heap, not to restrict size).

Thanks for the compliment!  And please do feel free to file any more issues for anything you think doesn't look right.

**Comment by KammererTob** [comment]
I understand. Thanks for the clarification. 
One followup (or should i open a new issue?): Does this really ensure that we are getting the k closest neighbors?
Imagine this: The bucket of the specified node has only k-2 elements in it. This means that we need at least 2 more elements from other buckets. In the current code those would get popped from the bucket to the left (lets suppose that it has enough elements). But we cannot ensure that those two elements we pop from the left bucket are really closest to the specified node without checking the remaining elements of the left bucket  (and even the first right bucket) first. The left/right bucket could contain elements which are closer to the specified node than the two popped nodes. This is because the k-buckets are ordered by time last seen instead of distance.

I am not sure about this and it would be very petty, but i still would be interested what you think about that.

**Comment by bmuller** [comment]
Hey @KammererTob - I had go digging a bit, so sorry for the delay in a response.  The short answer is no, it doesn't ensure we are getting the k closest neighbors - but that's OK.  The buckets are sorted by recency of contact (so nodes near the top of the bucket are ones that are more likely to be online).  We go back and forth from left/right buckets so we can go from the most recently seen node to least recently seen node - until we have `k` of them and then we sort based on distance (using the heap).

Let me know if you have any other questions or if any of this isn't clear (or looks wrong).  Thanks!
