### ISSUE TITLE
how to solve the problem about NAT?

### ISSUE THREAD

**Issue by jianzfb** [bmuller/kademlia#41]
Dear author, 
I'm a new comer in the P2P filed. I very like your kademlia and help me learn the pricinple of P2P network. But I have some problems:
In the real scene of P2P, node is behind NAT and I couldn't get its real IP. I dont know how to use server.bootstrap([bootstrap_node]), its arg must be node's IP.

**Comment by bmuller** [comment]
You must have at least one node that is not behind a NAT.  Any other nodes (even if they are behind a NAT) will be able to connect to that node.

**Comment by sivanagarajumolabant** [comment]
@bmuller  
server.bootstrap([bootstrap_node]) 
bootstrap_node means which node i have to pass here ,can you tell me?
