### ISSUE TITLE
Kademlia is dependent on Forgetful Storage

### ISSUE THREAD

**Issue by bretttjohnson1** [bmuller/kademlia#45]
Forgetful Storage should probably be the base class that is extended as it kademlia is dependent on the functions in it.
example: https://github.com/bmuller/kademlia/blob/master/kademlia/network.py#L98

**Comment by bmuller** [comment]
That method exists in the interface: https://github.com/bmuller/kademlia/blob/master/kademlia/storage.py#L30

**Comment by bretttjohnson1** [comment]
oops, my bad. Didn't see it for some reason.
