### ISSUE TITLE
Values in the DHT must be of specific types

### ISSUE THREAD

**Issue by bretttjohnson1** [bmuller/kademlia#46]
Values in the DHT must be hashable because of: 

https://github.com/bmuller/kademlia/blob/master/kademlia/crawling.py#L114

Values in the DHT must also be of types: bool, int, float, str, bytes, because of this function kademlia calls
https://github.com/vsergeev/u-msgpack-python/blob/master/umsgpack.py#L473.

**Comment by bmuller** [comment]
@bretttjohnson1 Are you saying this is a bug?

**Comment by bretttjohnson1** [comment]
It should be specified that this requirement exists somewhere. When setting values in the DHT to lists, it error-ed upon running the first function above. Then when correcting it to a hash-able type of frozenset, it error-ed in the second function mentioned. This should not be a 4 hour hunt for this behavior. It should be explicitly defined
