### ISSUE TITLE
Example in README.md is wrong

### ISSUE THREAD

**Issue by bretttjohnson1** [bmuller/kademlia#47]
A loop.run_forever() call is required to bring the Server online. This should be in the first example in the readme.

**Comment by bmuller** [comment]
The first example explicitly says:
> Assuming you want to connect to an existing network

And then sets a value on the network.  `run_forever` isn't required to do that.

**Comment by bretttjohnson1** [comment]
The example implies that this is how joining the DHT is done. If one would want to set up the server for repeated use, run_forever is required
