### ISSUE TITLE
Single node network

### ISSUE THREAD

**Issue by Rendaw** [bmuller/kademlia#5]
It looks like the server doesn't work with a single node due to line https://github.com/bmuller/kademlia/blob/master/kademlia/network.py#L166

I haven't read the original paper, but is there any reason this has to happen?  I was hoping to test locally with one instance in order to verify other (non DHT) parts of the program.

**Comment by bmuller** [comment]
I'm a little torn on this one, since it's a DHT and not a HT - but I think it might be useful to support single node networks.  I'll fix that.

**Comment by Rendaw** [comment]
It wasn't that difficult to work around once I realized what the issue was.  Maybe just a note in the docs that running only one node won't work?

**Comment by bmuller** [comment]
K - added note in docs.  I thought about it some more - and I think it should be a failure state if you are the only node in what should be a network.  I'm only marginally convinced of this, though - so if you'd like, feel free to reopen with your thoughts.
