### ISSUE TITLE
Example of concurrent tasks 

### ISSUE THREAD

**Issue by matthieugouel** [bmuller/kademlia#57]
Hi ! 

I'm trying to create an app that communicate thanks to Kademlia. This app have to do an extensive task when a key is updated on the network, so I think I have to do the extensive task _concurrently_ with the network listening. 

I have tried to do something like that but it doesn't seems to work. 

```python

async def main(server, blockchain):
    """Main loop."""
    while True:
        blockchain = await update_blockchain(server, blockchain)
        blockchain = await mine(blockchain)
        await update_blockchain(server, blockchain)

port = sys.argv[1]

server = Server()
server.listen(port)

loop = asyncio.get_event_loop()

bootstrap_node = [("localhost", 8468)]
loop.run_until_complete(server.bootstrap(bootstrap_node))

# Bootstrap the blockchain
blockchain = loop.run_until_complete(bootstrap_blockchain(server))
print("Blockchain bootstrapped with difficulty " + str(blockchain.difficulty))

print("Start mining...")
loop.create_task(main(server, blockchain))

try:
    loop.run_forever()
except KeyboardInterrupt:
    pass
finally:
    server.stop()
    loop.close()
```
Note: the `update_blockchain(...)` coroutine uses `server.get(...)` and `server.set(...)` to interact with the network. 

I think here the task is not concurrent with the listening because I receive messages like this : 

```
Did not received reply for msg id b'aGaXClwL0Y5BfZ4kzZvZShMx/gs=' within 5 seconds
no response from 127.0.0.1:8470, removing from router
received unknown message b'aGaXClwL0Y5BfZ4kzZvZShMx/gs=' from ('127.0.0.1', 8470); ignoring
```

I'm sure this question is more asyncio related than kademlia but maybe have you already thought about this kind of problem ? 

Cheers,
Matthieu.

**Comment by bmuller** [comment]
Hey @matthieugouel - without a full code example it's hard for me to diagnose, but based on your log output it looks like you're trying to perform a long running **blocking** synchronous task that's keeping a node from responding in time (the error saying the message response wasn't received in time, followed later by the message it was waiting for).  I would suggest you find a way to make that long running blocking task asynchronous.

**Comment by matthieugouel** [comment]
You were right, the task I was running was blocking, so it couldn't be performed asynchronously. 
For the record, I used a `ThreadPoolExecutor` to create an task executor and launched my blocking task via `loop.run_in_executor(executor, long_blocking_task)`. 
Cheers.
