### ISSUE TITLE
Asynchronous Server listening

### ISSUE THREAD

**Issue by matthieugouel** [bmuller/kademlia#58]
Hello ! 

I was wondering why the `listen(...)` method of the class `Server` is synchronous ? For a simpler integration with aiohttp I attempted to modify this method a little to make it asynchronous. This is what I did : 

```python
from kademlia.network import Server

class AsyncServer(Server):
    def __init__(self, *args, **kwargs):
        self.loop = kwargs.pop("loop", asyncio.get_event_loop())
        super().__init__(*args, **kwargs)

    async def listen(self, port, interface="0.0.0.0"):  # nosec
        """
        Start listening on the given port.
        Provide interface="::" to accept ipv6 address
        """
        listen = self.loop.create_datagram_endpoint(
            self._create_protocol, local_addr=(interface, port)
        )
        log.info("Node %i listening on %s:%i", self.node.long_id, interface, port)
        self.transport, self.protocol = await listen
        # finally, schedule refreshing table
        self.refresh_table()
```

As you can see I modified this line https://github.com/bmuller/kademlia/blob/master/kademlia/network.py#L71 to replace `loop.run_until_complete(...)` by `await listen`.

I don't fully see the impacts of this modification on the overall package but it seems to work pretty well for now. Is there a particular reason why you used `loop.run_until_complete(...)` method to do the listen ? 

I also changed the `__init__(...)` method to allow to pass a custom loop to the class. 

If you find that theses modifications make sense I would be happy to do a PR. 

Cheers, 
Matthieu.

**Comment by matthieugouel** [comment]
Actually to do the job entirely I also have to change the loop in the methods that use `loop.call_later(...)` (ie `.refresh_table(...)` and `saveStateRegulary(...)`)  so this is what i ended up : 

```python
class AsyncServer(Server):
    def __init__(self, *args, **kwargs):
        self.loop = kwargs.pop("loop", asyncio.get_event_loop())
        super().__init__(*args, **kwargs)

    async def listen(self, port, interface="0.0.0.0"):  # nosec
        """
        Start listening on the given port.
        Provide interface="::" to accept ipv6 address
        """
        listen = self.loop.create_datagram_endpoint(
            self._create_protocol, local_addr=(interface, port)
        )
        log.info("Node %i listening on %s:%i", self.node.long_id, interface, port)
        self.transport, self.protocol = await listen
        # finally, schedule refreshing table
        self.refresh_table()

    def refresh_table(self):
        log.debug("Refreshing routing table")
        asyncio.ensure_future(self._refresh_table())
        self.refresh_loop = self.loop.call_later(3600, self.refresh_table)

    def saveStateRegularly(self, fname, frequency=600):
        """
        Save the state of node with a given regularity to the given
        filename.
        Args:
            fname: File name to save retularly to
            frequency: Frequency in seconds that the state should be saved.
                        By default, 10 minutes.
        """
        self.saveState(fname)
        self.save_state_loop = self.loop.call_later(
            frequency, self.saveStateRegularly, fname, frequency
        )
```

By the way this last method `saveStateRegulary(...)` should be called `save_state_regulary(...)` according to PEP8.

**Comment by matthieugouel** [comment]
Hi ! Thanks for your response ! 

Actually, my thought about transforming `listen(...)` to an asynchronous method is more for confort. In particular it allows to do something like that the code bellow (python 3.7) whereas calling `Server` and `listen` outside the `main` async method. 

```python
import asyncio

from kademlia.network import Server


async def main():
    server = Server()
    await server.listen(8469)
    await server.bootstrap([("localhost", 8468)])
    await server.set("hello", "world")
    print(await server.get("hello"))


if __name__ == "__main__":
    asyncio.run(main())
```

But frankly it's surely an implementation detail and it's not hard for the user to override the method if he wants to do something like I did. So it's completely up to you.

For the method name `saveStateRegulary(...)` yes I'll do the PR as find the time ! I'm glad to help a little to this interesting project :) 

Cheers,
Matthieu.

**Comment by bmuller** [comment]
Hey @matthieugouel - thanks, that makes sense to me.  Feel free to send a PR with the updated `async listen` method and I'll happily merge.  Might be good to update the README/docs too.  I'll make this a part of a new release.  Thanks for the help - and I agree, making `listen` async would make the lib better - so thanks for the contribution!

**Comment by bmuller** [comment]
Fixed in #60

**Comment by sivanagarajumolabant** [comment]
@matthieugouel i need your help can you give your email id

**Comment by matthieugouel** [comment]
yes of course matthieu.gouel@gmail.com
