### ISSUE TITLE
Republishing example

### ISSUE THREAD

**Issue by Rendaw** [bmuller/kademlia#6]
To quote the readme: `in Section 2.3 there is the requirement that the original publisher of a key/value republish it every 24 hours. This library does not do this (though you can easily do this manually).`

Is republishing just calling [server.refreshTable()](http://kademlia.readthedocs.org/en/latest/source/kademlia.html#kademlia.network.Server.refreshTable)?  It seemed like that may be the case, but I didn't know if there was anything else that has to be done.

Also, it isn't clear from the documentation if refreshTable republishes all stored key/values or just key/values originally published by this node.  May the latter be assumed?

**Comment by bmuller** [comment]
`refreshTable` just updates its list of nodes and republishes *it's own* keys older than an hour.  The readme is talking about something different.  The republishing there is for any client software (not nodes, but users of the DHT) that care about a key mapping to a value republishing every 24 hours - which is different than what an individual node does with it's own keys.

**Comment by Rendaw** [comment]
Thank you for the help and the prompt response!

Is it sufficient to call server.set() for each originally published pair once a day then?

**Comment by bmuller** [comment]
Thanks!  Yep - that's all that's needed.
