### ISSUE TITLE
Possibility of Direct messaging / broadcast?

### ISSUE THREAD

**Issue by lsteffenel** [bmuller/kademlia#68]
Hello!
I have a question about using kademlia beyond a simple DHT storage. Indeed, I need both DHT and a messaging overlay, but I'm having trouble finding how to implement messaging over this library. I'm almost sure that there is a way using the RPC over UDP module, but I'm too dumb (ok, I came from the Java world and I previously used the TomP2P library).

Can you give me some hints on how to send messages between nodes? 

Thank you for your help!

**Comment by bmuller** [comment]
Hey @lsteffenel - you could create your own version of `kademlia.protocol.KademliaProtocol` (make a new class that extends it, and add your own additional RPC functions).  Then just set that class as the protocol used for the network ([here](https://github.com/bmuller/kademlia/blob/master/kademlia/network.py#L26)).  Then, after starting the network connection for a node, you can call `server.protocol.your_rpc_function(whatever)`.

**Comment by amirouche** [comment]
@lsteffenel for what is worth, I have made a fork of this project where I re-implemented storage and added a few more primitives, look at this [repository](https://framagit.org/amz3/qadom/blob/master/qadom/peer.py). You particular requirements to do messaging can be implemented in a similar way to [`get_at`](https://framagit.org/amz3/qadom/blob/master/qadom/peer.py#L559)
