### ISSUE TITLE
didn't find network

### ISSUE THREAD

**Issue by sivanagarajumolabant** [bmuller/kademlia#69]
how can i know the bootstrap node ip address and port , i pulled the code  , i run the your bootstrap node code it will keep on running ,while i run the same file with passing bootstrap node (i mean prevoius code ip and port )  then it is finding the node in my machine , when i run the different system it is not working , can you please give me clarity once

**Comment by bmuller** [comment]
@sivanagarajumolabant you must follow the issue template for this repo for any issues you create
