### ISSUE TITLE
after close my machine nodes not be available in the network i mean nodes not available in kbucket

### ISSUE THREAD

**Issue by sivanagarajumolabant** [bmuller/kademlia#71]
can anyone help me iam using this repository for to make a private blockchain because kademlia p2p protocol network is very great features so iam using this one  , if anyone knows can you send me the detailed info to siva.m504504@gmail.com

below i explained what i did sofar and also i attached the screenshots of each file output , i have some questions i given in the end of the page

--> in the firstnode.py  file i gave  only port is 5000 
        loop.run_until_complete(server.listen(5000)) 
   if i run that code it is giving nodeid, interface and port and it will keep on running only     
   because of we used run_forever()
     **output of firstnode.py file:**
      "2019-06-14 14:35:52 INFO  MainThread modules.network Node 
      1359752123986314333800961178562141229721419151290 listening on `0.0.0.0:5000"`
-->next in the set.py file i gave port is 6000 and here i have to pass the parameters
                loop.run_until_complete(server.listen(6000))
                bootstrap_node = (sys.argv[1], int(sys.argv[2]))
                loop.run_until_complete(server.bootstrap([bootstrap_node]))
                result = loop.run_until_complete(server.set(sys.argv[3], sys.argv[4]))
       "Usage: python set.py <bootstrap node> <bootstrap port> <key> <value>"
       **bootstrap node**: means it is my computer LAN IPaddress i.e "192.168.2.24"
       **bootstrap port**:  it is firstnode.py file port i.e 5000 i gave here
       **key**:  i.e 1
       **value**: i.e mykey
      command : python set.py 192.168.2.24 5000 1 mykey
  if i run that command it is giving nodeid,port,interface and also it is gatheresd the peers and n 
  nearest nodes in the network

![firstnode file output before running set py file](https://user-images.githubusercontent.com/50843337/59541373-c4978580-8eb5-11e9-9b0f-1b04ada1429d.jpg)

![set py file output](https://user-images.githubusercontent.com/50843337/59541374-c5301c00-8eb5-11e9-82c3-197b8ebdd8b9.jpg)

![first node file output after ran the set py file ](https://user-images.githubusercontent.com/50843337/59541371-c4978580-8eb5-11e9-85a0-4e0c1ac9fdc2.jpg)

sofar what i did it is correct, if any thing wrong can you tell me  

that's it sofar it was working but when i will close my machine that created nodes not available in the network because of if you create a new node it will gather the other nodes also if they are online but every time it will create a new nodes added into the router after closing my machine the nodes gone , where can i see my nodes i mean previously created nodes 

Questions:

Q1. is it my computer LAN  network ip address is my bootstrap node beacause i passed the 
   bootstrap node in the set.py file as a parameter
Q2. if my system shut down  the created nodes automatically removed , i dont't where that 
     nodes are saved in the network (i know bsically the nodes will be saved in the kbucket but 
     when i close my machine the nodes gone )?
Q3. if i run same code in the different machine is it both machines gathered the nodes too?but 
      not gathered
Q4  have you know how to hardcode the bootstrap ip ?
Q5  how to find out the bootstrap node from an existing network?

**Comment by bmuller** [comment]
Thank you for your interest in Kademlia.  It looks like you have some questions about the library that might be specific to a particular setup/use case, and unfortunately I don't have the time or availability to help in individual cases like yours.  Kademlia is offered entirely "as is" under the MIT License.

If you believe you've found a bug, please take a look at the list of outstanding items at https://github.com/bmuller/kademlia/issues and create a new issue if the problem hasn't already been reported.  Contributions and pull requests are always welcome as well; the library is a group effort from many contributors at this point.

Thanks for using open source software, and I wish you the best of luck

**Comment by sivanagarajumolabant** [comment]
can you please anyone mail id to help me  except JTucker@gmail.com
