### ISSUE TITLE
bug report : Remove nodes with same ip/port

### ISSUE THREAD

**Issue by rajmsnr** [bmuller/kademlia#72]
bug1:
 if i created a node with 5000 port when i run this file again it will give different node id with same port it means the port and node id are deleted
shouldn't a existing node with the same ip/port be deleted? 
what I mean is that a new node will be created and stored in the table even if it has already been stored before (which happens when the same node connects to the network multiple times, as a different id is created each time).

Q) network created through LAN is working but how to through WAN is not connecting , how can i do that?
Q)every network ip address is a bootstrap node?

**Comment by bmuller** [comment]
Thank you for your interest in Kademlia.  It looks like you have some questions about the library that might be specific to a particular setup/use case, and unfortunately I don't have the time or availability to help in individual cases like yours.  Kademlia is offered entirely "as is" under the MIT License.

If you believe you've found a bug, please take a look at the list of outstanding items at https://github.com/bmuller/kademlia/issues and create a new issue if the problem hasn't already been reported.  Contributions and pull requests are always welcome as well; the library is a group effort from many contributors at this point.

Thanks for using open source software, and I wish you the best of luck.
