### ISSUE TITLE
Can write permissions be set for keys on Kademlia?

### ISSUE THREAD

**Issue by quadrismegistus** [bmuller/kademlia#83]
Apologies if this not the right place for the question, and a bit of a newbie to kademlia. Is it possible to set write permissions for a key in a shared Kademlia store? I imagine this could be programmed manually in my client code -- e.g. verify private/public key of author/group match before allowing an overwrite -- but does that still leave open the possibility that another client could connect to the network and overwrite it anyway?

Thanks for reading this and thanks for this incredible package!

**Comment by bmuller** [comment]
Hey @quadrismegistus - you could limit writes by implementing your own version of [the IStorage interface](https://github.com/bmuller/kademlia/blob/master/kademlia/storage.py#L8) - and check for signed values, for instance.
