### ISSUE TITLE
Use package management tool like poetry

### ISSUE THREAD

**Issue by kigawas** [bmuller/kademlia#87]
Let's embrace `pyproject.toml`

**Comment by bmuller** [comment]
Per [PEP 518](https://www.python.org/dev/peps/pep-0518/):

> Because the use of setuptools and wheel are so expansive in the community at the moment, build tools are expected to use the example configuration file above as their default semantics when a pyproject.toml file is not present.

The default is sufficient for this project, since only setuptools is required.  I may add a pyproject.toml in the near future, even so.

RE poetry - I've reviewed the project and decided it's not a good fit.
